// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateMapTaskRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Inputs               []string `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	TaskId               string   `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ReduceSize           uint32   `protobuf:"varint,4,opt,name=reduce_size,json=reduceSize,proto3" json:"reduce_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMapTaskRequest) Reset()         { *m = CreateMapTaskRequest{} }
func (m *CreateMapTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMapTaskRequest) ProtoMessage()    {}
func (*CreateMapTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_97fc308cbef6f867, []int{0}
}
func (m *CreateMapTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMapTaskRequest.Unmarshal(m, b)
}
func (m *CreateMapTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMapTaskRequest.Marshal(b, m, deterministic)
}
func (dst *CreateMapTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMapTaskRequest.Merge(dst, src)
}
func (m *CreateMapTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMapTaskRequest.Size(m)
}
func (m *CreateMapTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMapTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMapTaskRequest proto.InternalMessageInfo

func (m *CreateMapTaskRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateMapTaskRequest) GetInputs() []string {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *CreateMapTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *CreateMapTaskRequest) GetReduceSize() uint32 {
	if m != nil {
		return m.ReduceSize
	}
	return 0
}

type CreateMapTaskResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	TaskId               string   `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMapTaskResponse) Reset()         { *m = CreateMapTaskResponse{} }
func (m *CreateMapTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMapTaskResponse) ProtoMessage()    {}
func (*CreateMapTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_97fc308cbef6f867, []int{1}
}
func (m *CreateMapTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMapTaskResponse.Unmarshal(m, b)
}
func (m *CreateMapTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMapTaskResponse.Marshal(b, m, deterministic)
}
func (dst *CreateMapTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMapTaskResponse.Merge(dst, src)
}
func (m *CreateMapTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMapTaskResponse.Size(m)
}
func (m *CreateMapTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMapTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMapTaskResponse proto.InternalMessageInfo

func (m *CreateMapTaskResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateMapTaskResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *CreateMapTaskResponse) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type CreateReduceTaskRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Inputs               []string `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	TaskId               string   `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ReduceRegionId       uint32   `protobuf:"varint,4,opt,name=reduce_region_id,json=reduceRegionId,proto3" json:"reduce_region_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReduceTaskRequest) Reset()         { *m = CreateReduceTaskRequest{} }
func (m *CreateReduceTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReduceTaskRequest) ProtoMessage()    {}
func (*CreateReduceTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_97fc308cbef6f867, []int{2}
}
func (m *CreateReduceTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReduceTaskRequest.Unmarshal(m, b)
}
func (m *CreateReduceTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReduceTaskRequest.Marshal(b, m, deterministic)
}
func (dst *CreateReduceTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReduceTaskRequest.Merge(dst, src)
}
func (m *CreateReduceTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReduceTaskRequest.Size(m)
}
func (m *CreateReduceTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReduceTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReduceTaskRequest proto.InternalMessageInfo

func (m *CreateReduceTaskRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateReduceTaskRequest) GetInputs() []string {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *CreateReduceTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *CreateReduceTaskRequest) GetReduceRegionId() uint32 {
	if m != nil {
		return m.ReduceRegionId
	}
	return 0
}

type CreateReduceTaskResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	TaskId               string   `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReduceTaskResponse) Reset()         { *m = CreateReduceTaskResponse{} }
func (m *CreateReduceTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReduceTaskResponse) ProtoMessage()    {}
func (*CreateReduceTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_97fc308cbef6f867, []int{3}
}
func (m *CreateReduceTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReduceTaskResponse.Unmarshal(m, b)
}
func (m *CreateReduceTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReduceTaskResponse.Marshal(b, m, deterministic)
}
func (dst *CreateReduceTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReduceTaskResponse.Merge(dst, src)
}
func (m *CreateReduceTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReduceTaskResponse.Size(m)
}
func (m *CreateReduceTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReduceTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReduceTaskResponse proto.InternalMessageInfo

func (m *CreateReduceTaskResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateReduceTaskResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *CreateReduceTaskResponse) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateMapTaskRequest)(nil), "CreateMapTaskRequest")
	proto.RegisterType((*CreateMapTaskResponse)(nil), "CreateMapTaskResponse")
	proto.RegisterType((*CreateReduceTaskRequest)(nil), "CreateReduceTaskRequest")
	proto.RegisterType((*CreateReduceTaskResponse)(nil), "CreateReduceTaskResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the samples package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerServerClient is the client API for WorkerServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerServerClient interface {
	CreateMapTask(ctx context.Context, in *CreateMapTaskRequest, opts ...grpc.CallOption) (*CreateMapTaskResponse, error)
	CreateReduceTask(ctx context.Context, in *CreateReduceTaskRequest, opts ...grpc.CallOption) (*CreateReduceTaskResponse, error)
}

type workerServerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerServerClient(cc *grpc.ClientConn) WorkerServerClient {
	return &workerServerClient{cc}
}

func (c *workerServerClient) CreateMapTask(ctx context.Context, in *CreateMapTaskRequest, opts ...grpc.CallOption) (*CreateMapTaskResponse, error) {
	out := new(CreateMapTaskResponse)
	err := c.cc.Invoke(ctx, "/WorkerServer/CreateMapTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServerClient) CreateReduceTask(ctx context.Context, in *CreateReduceTaskRequest, opts ...grpc.CallOption) (*CreateReduceTaskResponse, error) {
	out := new(CreateReduceTaskResponse)
	err := c.cc.Invoke(ctx, "/WorkerServer/CreateReduceTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServerServer is the server API for WorkerServer service.
type WorkerServerServer interface {
	CreateMapTask(context.Context, *CreateMapTaskRequest) (*CreateMapTaskResponse, error)
	CreateReduceTask(context.Context, *CreateReduceTaskRequest) (*CreateReduceTaskResponse, error)
}

func RegisterWorkerServerServer(s *grpc.Server, srv WorkerServerServer) {
	s.RegisterService(&_WorkerServer_serviceDesc, srv)
}

func _WorkerServer_CreateMapTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMapTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServerServer).CreateMapTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WorkerServer/CreateMapTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServerServer).CreateMapTask(ctx, req.(*CreateMapTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerServer_CreateReduceTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReduceTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServerServer).CreateReduceTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WorkerServer/CreateReduceTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServerServer).CreateReduceTask(ctx, req.(*CreateReduceTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkerServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "WorkerServer",
	HandlerType: (*WorkerServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMapTask",
			Handler:    _WorkerServer_CreateMapTask_Handler,
		},
		{
			MethodName: "CreateReduceTask",
			Handler:    _WorkerServer_CreateReduceTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}

func init() { proto.RegisterFile("worker.proto", fileDescriptor_worker_97fc308cbef6f867) }

var fileDescriptor_worker_97fc308cbef6f867 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xeb, 0x04, 0x0a, 0x1c, 0x6d, 0x55, 0x59, 0xb4, 0x35, 0x5d, 0x88, 0x3c, 0x65, 0xca,
	0x00, 0x7f, 0x00, 0xc1, 0x94, 0x81, 0xc5, 0x45, 0x02, 0xc1, 0x50, 0x05, 0x7c, 0x42, 0x56, 0x50,
	0x62, 0x6c, 0x07, 0x50, 0x67, 0xfe, 0x05, 0x7f, 0x16, 0xc5, 0xc9, 0x42, 0x9b, 0x6c, 0x1d, 0xdf,
	0x4b, 0x74, 0xef, 0xbe, 0x77, 0x86, 0xd1, 0x57, 0x69, 0x72, 0x34, 0x89, 0x36, 0xa5, 0x2b, 0xf9,
	0x37, 0x9c, 0xdd, 0x1a, 0xcc, 0x1c, 0xde, 0x65, 0xfa, 0x3e, 0xb3, 0xb9, 0xc0, 0x8f, 0x0a, 0xad,
	0xa3, 0x13, 0x08, 0x94, 0x64, 0x24, 0x22, 0xf1, 0x58, 0x04, 0x4a, 0xd2, 0x39, 0x0c, 0x55, 0xa1,
	0x2b, 0x67, 0x59, 0x10, 0x85, 0xf1, 0x89, 0x68, 0x15, 0x5d, 0xc0, 0x91, 0xcb, 0x6c, 0xbe, 0x56,
	0x92, 0x85, 0x11, 0xa9, 0x3f, 0xd4, 0x32, 0x95, 0xf4, 0x02, 0x4e, 0x0d, 0xca, 0xea, 0x15, 0xd7,
	0x56, 0x6d, 0x90, 0x1d, 0xf8, 0x49, 0xd0, 0x58, 0x2b, 0xb5, 0x41, 0xfe, 0x08, 0xb3, 0xad, 0x64,
	0xab, 0xcb, 0xc2, 0x62, 0x57, 0xb4, 0x41, 0x5b, 0xbd, 0x3b, 0x16, 0x44, 0x24, 0x3e, 0x16, 0xad,
	0xea, 0x8d, 0xe6, 0x3f, 0x04, 0x16, 0xcd, 0x68, 0xe1, 0xe3, 0xf6, 0xca, 0x15, 0xc3, 0xb4, 0xe5,
	0x32, 0xf8, 0xa6, 0xca, 0xa2, 0xfe, 0xa3, 0x81, 0x9b, 0x34, 0xbe, 0xf0, 0x76, 0x2a, 0xf9, 0x33,
	0xb0, 0xdd, 0x2d, 0xf6, 0xc4, 0x78, 0xf9, 0x4b, 0x60, 0xf4, 0xe0, 0x0f, 0xb9, 0x42, 0xf3, 0x89,
	0x86, 0x5e, 0xc3, 0xf8, 0x5f, 0x9d, 0x74, 0x96, 0x74, 0x1d, 0x76, 0x39, 0x4f, 0x3a, 0x5b, 0xe7,
	0x03, 0x9a, 0xc2, 0x74, 0x7b, 0x5f, 0xca, 0x92, 0x9e, 0x22, 0x97, 0xe7, 0x49, 0x1f, 0x1c, 0x1f,
	0xdc, 0x1c, 0x3e, 0x85, 0x99, 0x56, 0x2f, 0x43, 0xff, 0xc6, 0xae, 0xfe, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xaf, 0x6c, 0xab, 0xb8, 0x73, 0x02, 0x00, 0x00,
}
